pool:
  name: Azure Pipelines
steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore Nuget'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet Test'
  inputs:
    command: test
    projects: '**/*.csproj'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
